Documentation:
  Enabled: false

AllCops:
  RunRailsCops: true
  Include:
    - Gemfile
    - lib/tasks/*
  Exclude:
    - db/schema.rb
    - vendor/**/*

Lint/AssignmentInCondition:
  Enabled: false

Lint/HandleExceptions:
  Enabled: false
