source 'https://rubygems.org'

gem 'coffee-rails', '~> 4.0.0'
gem 'eefgilm'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'minitest-rails'
gem 'rails', '4.1.6'
gem 'sass-rails', '~> 4.0.3'
gem 'spring', group: :development
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'
gem 'selenium-webdriver'
gem 'foundation-rails', '5.4.0'
gem 'font-awesome-rails'

group :development do
  gem 'rails_layout'
  gem 'sqlite3'
end

group :doc do
  gem 'sdoc', require: false
end

group :production do
  gem 'rails_12factor'
  gem 'pg'
end

group :test do
  gem 'minitest-rails-capybara'
end
